import type { Metadata } from 'next';
import { Nanum_Myeongjo, Nunito, Oooh_Baby } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import './globals.css';

import AuthListener from '@/components/AuthListener';
import HeaderNav from '@/components/navigation/HeaderNav';

import ManualDataGridContainer from '../features/ManualDataGrid/ManualDataGridContainer';

import Provider from './provider';

const nunitoSans = Nunito({
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

const nanumMyeongjo = Nanum_Myeongjo({
  weight: ['400', '700'],
  variable: '--font-nanum-myeongjo',
  subsets: ['latin'],
});

const ooohBaby = Oooh_Baby({
  weight: '400',
  variable: '--font-oooh-baby',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Healthabitify - Sustainifying Health Habits',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.jpg',
    shortcut: '/favicon.jpg',
    apple: '/apple-touch-icon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${nunitoSans.variable} ${nanumMyeongjo.variable} ${ooohBaby.variable} antialiased`}
      >
        <ToastContainer
          position='top-center'
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme='light'
          limit={3}
        />
        <Provider>
          <>
            <HeaderNav />
            <AuthListener />
            {children}
            <ManualDataGridContainer />
          </>
        </Provider>
      </body>
    </html>
  );
}
