import type { Metadata } from "next";
import { Nunito, Nanum_Myeongjo } from "next/font/google";
import "./globals.css";
import Provider from './provider'
import { ToastContainer } from "react-toastify";
import HeaderNav from "@/components/HeaderNav";

const nunitoSans = Nunito({
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const nanumMono = Nanum_Myeongjo({
  weight: ['400', '700'],
  variable: "--font-nanum-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Healthabitify - Sustainifying Health Habits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} ${nanumMono.variable} antialiased`}>
        <Provider>
          <>
            <ToastContainer 
                position="top-center"
                autoClose={5000}
            />
            <HeaderNav />
            {children}
          </></Provider>
      </body>
    </html>
  );
}
